In [1]:
import numpy as ny

Write a function so that the columns of the output matrix are powers of the input
vector.
<br>
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
<br>
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [128]:
x=ny.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [117]:
def gen_Matrix(arr,n,srt):
    if srt:
        otm=ny.array([x**i for x in arr for i in range(n)]).reshape(arr.size,n)
    else:
        otm=ny.array([x**(n-1-i) for x in arr for i in range(n)]).reshape(arr.size,n)
        
    return otm

In [129]:
Output_matrix=gen_Matrix(x,3,True)
Output_matrix

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  4, 16],
       [ 1,  5, 25]])

In [130]:
Output_matrix1=gen_Matrix(x,3,False)
Output_matrix1

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1],
       [25,  5,  1]])

Problem Statement 2:
<br>
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
<br>
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below<br>
i 1 2 3 4 5 6 7 8 9 10<br>
===== == == == == == == == == == ==<br>
Input 10 20 30 40 50 60 70 80 90 100<br>
y1 25 = (10+20+30+40)/4<br>
y2 35 = (20+30+40+50)/4<br>
y3 45 = (30+40+50+60)/4<br>
y4 55 = (40+50+60+70)/4<br>
y5 65 = (50+60+70+80)/4<br>
y6 75 = (60+70+80+90)/4<br>
y7 85 = (70+80+90+100)/4<br>
Thus, the moving average sequence has n-k+1=10-4+1=7 values.<br>
Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [188]:
arr=ny.array([3,5,7,2,8,10,11,65,72,81,99,100,150])
window=3

In [186]:
arr

array([  3,   5,   7,   2,   8,  10,  11,  65,  72,  81,  99, 100, 150])

In [182]:
def avg_seq(arr,window):
    n=arr.size
    iteration=n-window+1
    for i in range(0,iteration):
        print(round(arr[i:i+window].sum()/window))
   

In [189]:
avg_seq(arr,window)

5
5
6
7
10
29
49
73
84
93
116
